bitzy:
  url: http://localhost:8081
server:
    port: 8081
spring: 
  profiles:
    active: in-memory
  datasource:
    db1:
      jdbc-url: jdbc:h2:mem:testdb
      user: sa
      password: password
      driverClassName: org.h2.Driver
    db2:
      jdbc-url: jdbc:h2:mem:testdb
      user: sa
      password: password
      driverClassName: org.h2.Driver